wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    code_path: code/train.py
    framework: huggingface
    huggingface_version: 4.23.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1671899962.9841
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 41
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 41
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.9.13
      5: 0.13.7
      6: 4.23.1
      8:
      - 5
architecture:
  desc: null
  value: SKNet26
batch_size:
  desc: null
  value: 16
dataset:
  desc: null
  value: COVID-19 Radiography
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.0005
weight_decay:
  desc: null
  value: 0
